apiVersion: v1
kind: Secret
metadata:
  name: device-postgres-secret
  namespace: device-login
type: Opaque
stringData:
  POSTGRES_DB: device_login
  POSTGRES_USER: device_login
  POSTGRES_PASSWORD: device_login_password
